//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.App.Resources.MessagesText", typeof(MessagesText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KFlearning.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hak Cipta (C) Fahmi Noor Fiqri {0}.
        ///Dilisensikan di bawah lisensi MIT..
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateProjectDuplicateError {
            get {
                return ResourceManager.GetString("CreateProjectDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateProjectNameEmptyError {
            get {
                return ResourceManager.GetString("CreateProjectNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenis proyek yang dipilih tidak diketahui..
        /// </summary>
        internal static string CreateProjectNullProjectTypeError {
            get {
                return ResourceManager.GetString("CreateProjectNullProjectTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikasi mengalami crash dan harus ditutup. Harap laporkan kepada asprak..
        /// </summary>
        internal static string FatalShutdown {
            get {
                return ResourceManager.GetString("FatalShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flutter terdeteksi pada sistem. Anda tidak perlu install Flutter lagi..
        /// </summary>
        internal static string FlutterAlreadyInstalledError {
            get {
                return ResourceManager.GetString("FlutterAlreadyInstalledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat menemukan folder. Coba buka dari folder..
        /// </summary>
        internal static string HomeProjectNotFoundError {
            get {
                return ResourceManager.GetString("HomeProjectNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membuka atau membuat project, coba ganti nama atau buka dari folder..
        /// </summary>
        internal static string HomeProjectOpenCreateError {
            get {
                return ResourceManager.GetString("HomeProjectOpenCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KF-MinGW belum di install, silakan install terlebih dahulu!.
        /// </summary>
        internal static string KFmingwNotInstalled {
            get {
                return ResourceManager.GetString("KFmingwNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/fahminlb33.
        /// </summary>
        internal static string LinksGithub {
            get {
                return ResourceManager.GetString("LinksGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kodesiana.com.
        /// </summary>
        internal static string LinksHomepage {
            get {
                return ResourceManager.GetString("LinksHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/in/fahmi-noor-fiqri/.
        /// </summary>
        internal static string LinksLinkedin {
            get {
                return ResourceManager.GetString("LinksLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KFlearning sudah berjalan, cek taskbar kamu!.
        /// </summary>
        internal static string SingleInstanceError {
            get {
                return ResourceManager.GetString("SingleInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Code belum di install, silakan install terlebih dahulu!.
        /// </summary>
        internal static string VSCodeNotInstalled {
            get {
                return ResourceManager.GetString("VSCodeNotInstalled", resourceCulture);
            }
        }
    }
}
