//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.Services.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.Services.Templates.TR", typeof(TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;configurations&quot;: [{
        ///        &quot;name&quot;: &quot;MinGW&quot;,
        ///        &quot;intelliSenseMode&quot;: &quot;gcc-x86&quot;,
        ///        &quot;compilerPath&quot;: &quot;{GXX}&quot;,
        ///        &quot;includePath&quot;: [
        ///            &quot;${workspaceFolder}/**&quot;,
        ///            &quot;{ENV1}/**&quot;,
        ///            &quot;{ENV2}/**&quot;
        ///        ],
        ///        &quot;defines&quot;: [
        ///            &quot;_DEBUG&quot;,
        ///            &quot;UNICODE&quot;
        ///        ],
        ///        &quot;cStandard&quot;: &quot;c11&quot;,
        ///        &quot;cppStandard&quot;: &quot;c++17&quot;
        ///    }],
        ///    &quot;version&quot;: 4
        ///}.
        /// </summary>
        internal static string CPP_c_cpp_properties {
            get {
                return ResourceManager.GetString("CPP_c_cpp_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    // See https://go.microsoft.com/fwlink/?LinkId=733558
        ///    // for the documentation about the tasks.json format
        ///    &quot;version&quot;: &quot;2.0.0&quot;,
        ///    &quot;tasks&quot;: [{
        ///        &quot;label&quot;: &quot;Build&quot;,
        ///        &quot;type&quot;: &quot;shell&quot;,
        ///        &quot;command&quot;: &quot;g++&quot;,
        ///        &quot;args&quot;: [
        ///          &quot;-g&quot;, &quot;${relativeFile}&quot;, &quot;-o&quot;, &quot;${fileBasenameNoExtension}.exe&quot;
        ///        ],
        ///        &quot;group&quot;: {
        ///            &quot;kind&quot;: &quot;build&quot;,
        ///            &quot;isDefault&quot;: true
        ///        }
        ///    }]
        ///}.
        /// </summary>
        internal static string CPP_Console_tasks {
            get {
                return ResourceManager.GetString("CPP_Console_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    // See https://go.microsoft.com/fwlink/?LinkId=733558
        ///    // for the documentation about the tasks.json format
        ///    &quot;version&quot;: &quot;2.0.0&quot;,
        ///    &quot;tasks&quot;: [{
        ///        &quot;label&quot;: &quot;Build&quot;,
        ///        &quot;type&quot;: &quot;shell&quot;,
        ///        &quot;command&quot;: &quot;g++&quot;,
        ///        &quot;args&quot;: [
        ///          &quot;-g&quot;, &quot;${relativeFile}&quot;, &quot;-mwindows&quot;, &quot;-lopengl32&quot;, &quot;-lglew32&quot;, &quot;-lfreeglut&quot;, &quot;-lglu32&quot;, &quot;-o&quot;, &quot;${fileBasenameNoExtension}.exe&quot;
        ///        ],
        ///        &quot;group&quot;: {
        ///            &quot;kind&quot;: &quot;build&quot;,
        ///            &quot;isDefault&quot;: true
        ///        }
        ///    }]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPP_GUI_tasks {
            get {
                return ResourceManager.GetString("CPP_GUI_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;version&quot;: &quot;0.2.0&quot;,
        ///    &quot;configurations&quot;: [{
        ///        &quot;name&quot;: &quot;Launch without Debugging&quot;,
        ///        &quot;type&quot;: &quot;cppvsdbg&quot;,
        ///        &quot;request&quot;: &quot;launch&quot;,
        ///        &quot;program&quot;: &quot;${fileBasenameNoExtension}.exe&quot;,
        ///        &quot;args&quot;: [],
        ///        &quot;stopAtEntry&quot;: false,
        ///        &quot;cwd&quot;: &quot;${workspaceFolder}&quot;,
        ///        &quot;environment&quot;: [],
        ///        &quot;externalConsole&quot;: true,
        ///        &quot;preLaunchTask&quot;: &quot;Build&quot;
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Launch using GDB&quot;,
        ///        &quot;type&quot;: &quot;cppdbg&quot;,
        ///        &quot;request&quot;: &quot;launch&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPP_launch {
            get {
                return ResourceManager.GetString("CPP_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Hello World.
        /// </summary>
        internal static string CPP_program {
            get {
                return ResourceManager.GetString("CPP_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;files.associations&quot;: {
        ///        &quot;*.tcc&quot;: &quot;cpp&quot;,
        ///        &quot;cctype&quot;: &quot;cpp&quot;,
        ///        &quot;clocale&quot;: &quot;cpp&quot;,
        ///        &quot;cstdint&quot;: &quot;cpp&quot;,
        ///        &quot;cstdio&quot;: &quot;cpp&quot;,
        ///        &quot;cstdlib&quot;: &quot;cpp&quot;,
        ///        &quot;cwchar&quot;: &quot;cpp&quot;,
        ///        &quot;cwctype&quot;: &quot;cpp&quot;,
        ///        &quot;exception&quot;: &quot;cpp&quot;,
        ///        &quot;fstream&quot;: &quot;cpp&quot;,
        ///        &quot;initializer_list&quot;: &quot;cpp&quot;,
        ///        &quot;iosfwd&quot;: &quot;cpp&quot;,
        ///        &quot;iostream&quot;: &quot;cpp&quot;,
        ///        &quot;istream&quot;: &quot;cpp&quot;,
        ///        &quot;limits&quot;: &quot;cpp&quot;,
        ///        &quot;new&quot;: &quot;cpp&quot;,
        ///        &quot;ostream&quot;: &quot;cpp&quot;,
        ///        &quot;stdexcept&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPP_settings {
            get {
                return ResourceManager.GetString("CPP_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print(&quot;Hello World&quot;).
        /// </summary>
        internal static string PY_program {
            get {
                return ResourceManager.GetString("PY_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello World. Hari ini &lt;?php echo date(&quot;d/m/Y&quot;);?&gt;&lt;/p&gt;.
        /// </summary>
        internal static string WEB_index {
            get {
                return ResourceManager.GetString("WEB_index", resourceCulture);
            }
        }
    }
}
