name: Canary Build
on: 
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build KFlearning (canary)
    runs-on: windows-latest
    
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: 'recursive'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.101'
        include-prerelease: true

    - name: Build 32-bit KFlearning...
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
        target: all
        arguments: |
            configuration: Debug
            platform: x86

    - name: Build 64-bit KFlearning...
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
        target: all
        arguments: |
            configuration: Debug
            platform: x64

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: KFlearning Installer
        path: build/*.msi

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "canary"
        prerelease: true
        title: "Canary Build"
        files: build/*.msi