name: Canary Build
on: 
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build-Incremental
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: 'recursive'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Run Cake Build
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
        target: Build-All
        arguments: |
            configuration: Release

    - name: Upload KFlearning Setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: KFlearning Installer
        path: build/KFlearning.Setup.msi
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "canary"
        prerelease: true
        title: "Canary Build"
        files: build/*.msi