name: Stable Build
on: 
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build-Incremental
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: 'recursive'

    - name: Replace environment vars
      uses: shitiomatic/str-replace@master
      with:
        find: "KFLEARNING_API_KEY"
        replace: "${{ secrets.KFLEARNING_API_KEY }}"

    - name: Run Cake Build
      run: PowerShell.exe -ExecutionPolicy Bypass -File ./build.ps1 --target Build-Incremental --configuration Release

    - name: Upload KFlearning Setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: KFlearning Installer
        path: build/KFlearning.Setup.msi

    - name: Upload KFmaintenance Setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: KFmaintenance Installer
        path: build/KFmaintenance.Setup.msi

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: build/*.msi