name: Stable Build
on: 
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build-Incremental
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: 'recursive'

    - name: Run Cake Build
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
        target: Build-All
        arguments: |
            configuration: Release

    - name: Upload KFlearning Setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: KFlearning Installer
        path: build/KFlearning.Setup.msi

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: build/*.msi